# Generated by Django 3.0.7 on 2020-07-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Call_Number', models.CharField(help_text='Enter the Call Number associated with the manumission document', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alt_spelling_first_name', models.CharField(max_length=100)),
                ('alt_spelling_last_name', models.CharField(max_length=100)),
                ('abbreviated_first_name', models.CharField(max_length=100)),
                ('abbreviated_last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='Name',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AddField(
            model_name='document',
            name='Call_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Call_Number'),
        ),
        migrations.AddField(
            model_name='person',
            name='Person_Name',
            field=models.ManyToManyField(help_text='Select the name for this person', to='catalog.Person_Name'),
        ),
    ]
