# Generated by Django 3.0.7 on 2020-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200722_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
