# Generated by Django 3.0.7 on 2020-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200724_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age_freed',
            old_name='Age_Freed',
            new_name='age_freed',
        ),
        migrations.RenameField(
            model_name='age_listed',
            old_name='Age_Listed',
            new_name='age_listed',
        ),
        migrations.RenameField(
            model_name='birth_place',
            old_name='Birth_Place',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='call_number',
            old_name='Call_Number',
            new_name='call_number',
        ),
        migrations.RenameField(
            model_name='death_place',
            old_name='Death_Place',
            new_name='death_place',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Call_Number',
            new_name='call_number',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='date_of_Manumission_Signing',
            new_name='date_of_manumission_signing',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Image_name',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Monthly_Meeting',
            new_name='monthly_meeting',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Page_Number',
            new_name='page_number',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='monthly_meeting',
            old_name='Monthly_Meeting',
            new_name='monthly_meeting',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Birth_Place',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Death_Place',
            new_name='death_place',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Place_Freed',
            new_name='place_freed',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='place_freed',
            old_name='Place_Freed',
            new_name='place_freed',
        ),
        migrations.RenameField(
            model_name='year_manumitted',
            old_name='Year_Manumitted',
            new_name='year_manumitted',
        ),
        migrations.RemoveField(
            model_name='birth_place',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='death_place',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Age_Freed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Age_Listed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Year_Manumitted',
        ),
        migrations.AddField(
            model_name='person',
            name='age_freed',
            field=models.CharField(blank=True, help_text='Age when freedom occured', max_length=3, verbose_name='Age_Freed'),
        ),
        migrations.AddField(
            model_name='person',
            name='age_listed',
            field=models.CharField(blank=True, help_text='Age listed on the Manumission Document', max_length=3, verbose_name='Age_Listed'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_manumitted',
            field=models.CharField(blank=True, help_text='Year when freedom occured', max_length=4, verbose_name='Year Manumission took effect'),
        ),
    ]
