# Generated by Django 3.0.7 on 2020-07-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200729_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
