# Generated by Django 3.0.7 on 2020-07-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200729_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RenameField(
            model_name='image_name',
            old_name='name',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='page_number',
            old_name='name',
            new_name='page_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='image_name',
        ),
        migrations.AddField(
            model_name='document',
            name='image_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Image_name'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='page_number',
        ),
        migrations.AddField(
            model_name='document',
            name='page_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Page_Number'),
        ),
    ]
