# Generated by Django 3.0.7 on 2020-07-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200730_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manumission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('date_of_manumission_signing', models.DateField(blank=True, null=True)),
                ('call_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Call_Number')),
                ('image_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Image_name')),
                ('monthly_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Monthly_Meeting')),
                ('page_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Page_Number')),
                ('person', models.ManyToManyField(help_text='Select Persons for this Manumission', to='catalog.Person')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
