# Generated by Django 3.0.7 on 2020-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200730_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_freed',
            field=models.CharField(blank=True, help_text='Age when freedom occured', max_length=5, verbose_name='Age_Freed'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age_listed',
            field=models.CharField(blank=True, help_text='Age listed on the Manumission Document', max_length=5, verbose_name='Age_Listed'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
